### ISSUE TITLE
No such module EdgeEngine

### ISSUE THREAD

**Issue by hoseinfo** [mimikgit/random-number-generator-iOS#1]
facing No such module EdgeEngine error when I clone project and switch to complete code and install pods.

**Comment by mimikrb** [comment]
Hello @hoseinfo 
Thank you for your interest.
Please make sure you have a real iOS device connected to Xcode and have it selected it as the target  (see the screenshots below)
Also there were some updates to the code branches today, so you might want to try again.

Below are some screenshots from our test today, please let us know if anything you see differs from the expected outcomes, in case you continue having trouble.

![setup-1](https://github.com/user-attachments/assets/ff96eb43-c433-490e-8de9-a40d5c7e74fb)
![setup-2](https://github.com/user-attachments/assets/6d5f9b29-0ee8-49c9-ac85-f235406d1ed4)

**Comment by hoseinfo** [comment]
thanks for your response, I run the app but getting this error: ( Error: not a valid license )

I got Developer-ID-Token from my project console and also my license from console ( please review images below )

<img width="556" alt="error" src="https://github.com/user-attachments/assets/b51f1842-009a-4756-8f7a-7f0c7615caef">

<img width="1195" alt="id token" src="https://github.com/user-attachments/assets/15068403-7048-4903-9297-e97351b4c7d9">

<img width="1195" alt="edge lineces" src="https://github.com/user-attachments/assets/0f41c447-3b39-4803-a8b3-c5276e1dfdd3">

**Comment by mimikrb** [comment]
ok, good progress @hoseinfo 
this means you got past the initial "No such module EdgeEngine" error.

For the mimOE (Edge) license issue, please try the following:

1. removing the installed example application from your device and starting over from scratch.
2. making sure there are no white spaces in the ```Developer-ID-Token``` and ```Developer-mimOE-License``` config files anywhere. Either leading or trailing. And that the value fills the whole file, end to end. No spaces anywhere.
3. making sure that the Developer ID Token and mimOE (Edge) license are the only content in the ```Developer-ID-Token``` and ```Developer-mimOE-License``` config file. There is no "<DEVELOPER-ID-TOKEN-FROM" left overs in them for example.

Please let us know how this goes.
If the config file loading fails, you could always copy/paste the id and license values into your code directly as Static String and bypass the config file loading altogether.

Attaching screenshot for illustration:
![setup-3](https://github.com/user-attachments/assets/37133be6-5af6-480f-b28b-e3f931a532d2)

**Comment by hoseinfo** [comment]
thanks, I put token and license directly in codes, the problem was it was not able to get them from files that you mentioned.

But for my last question, in your example you are just getting data from randomnumber micro service that we have, can I send data to micro service and do some process on inputs?

and also where is codes for  randomnumber micro service?

**Comment by mimikrb** [comment]
Fantastic! Great to see you got things working @hoseinfo 

This particular example edge microservice is called **randomnumber** only has one endpoint called **/randomNumber** on it. It is a GET endpoint, which returns a random number. There are no other endpoints.
Unfortunately, we don't have the source code for it available on GitHub.

However, we have posted source code for quite a few other edge microservices. You can see them here: https://github.com/edgeMicroservice

Also there is a new mimik AI chat example application, showing how to integrate AI language models into a mobile app. Check it out, it's pretty cool: https://github.com/mimikgit/mimik-ai-chat-example-iOS 

For developer documentation go here: https://devdocs.mimik.com

Please don't hesitate to get in touch with mimik, if you have any other questions: https://console.mimik.com/support

**Comment by hoseinfo** [comment]
I tried to build starter microservice and provide .tar file from it and use in iOS application.

1) I got .tar file
2) I run iOS app with random number sample
facing this error when I change .tar file and change the name in codes.
code:
Bundle.main.path(forResource: "microservice-v1-1.0.3", ofType: "tar")

Error:
nw_resolver_start_query_timer_block_invoke [C2.1.1] Query fired: did not receive all answers in time for [devconsole-mid.mimik.com:443](http://devconsole-mid.mimik.com:443/)

**Comment by mimikrb** [comment]
If you just replace one .tar for another this is not going to work. You also need to make sure the edge microservice deployment configuration matches the starter microservice. And adjust the response processing for the expected output from the edge microservice.

Also make sure you have up to date, developer id token and edge license (from https://console.mimik.com and that they are not expired.

May I suggest going through these tutorial to learn more about edge microservice deployment?
https://devdocs.mimik.com/tutorials/01-submenu/02-submenu
Specifically, the fourth one called "Working with edge microservices in an iOS project".

**Comment by mimikrb** [comment]
Thank you for your further interest @hoseinfo 

If you just replace one .tar for another this is not going to work. You also need to make sure the edge microservice deployment configuration matches the starter microservice. And adjust the response processing for the expected output from the edge microservice.

Also make sure you have up to date, developer id token and edge license (from https://console.mimik.com and that they are not expired.

May I suggest going through these tutorial to learn more about edge microservice deployment?
https://devdocs.mimik.com/tutorials/01-submenu/02-submenu
Specifically, the fourth one called "Working with edge microservices in an iOS project".
